### ISSUE TITLE
Stale Ingress certificates after Ingress resource is deleted

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1020]
Certifs are still there after resource is deleted:

$ kubectl exec istio-ingress-1709403620-m1czk -n istio12 -- ls /etc/istio/ingress-certs
tls.crt
tls.key

**Comment by rshriram** [comment]
close if no longer valid

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1392](https://github.com/istio/istio/issues/1392) via [**ZenHub**](https://www.zenhub.com/)
