### ISSUE TITLE
Ingress Status is updated with Pilot's address instead of Ingress controller's node address

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1021]
Observed by debugging the Ingress Status gets updated with the node where the pilot discovery pod is scheduled, and it should be updated with the node where the ingress-controller pod is scheduled.

**Comment by ijsnellf** [comment]
Did you verify that `IngressService` was set correctly in the ConfigMap? I assume this occurs when `IngressService` has not been set, in which case it is a bug.

**Comment by andraxylia** [comment]
This is for when Ingress is deployed as NodePort. In that case, the external IP of the service is not used. Please go inside k8s code and check.

**Comment by ijsnellf** [comment]
As per @andraxylia's suggestion, it may be possible to fix this by writing our own implementation of this line:
https://github.com/istio/pilot/blob/master/adapter/config/ingress/status.go#L87

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1387](https://github.com/istio/istio/issues/1387) via [**ZenHub**](https://www.zenhub.com/)
