### ISSUE TITLE
Need finer-grain logs on pilot, from 1-4

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1028]
Envoy debug is turned on on pilot log 3, and generates lots of logs.
We need finer-grain logs on pilot, from 1-4, and turn envoy debug on for logs on 5.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1395](https://github.com/istio/istio/issues/1395) via [**ZenHub**](https://www.zenhub.com/)
