### ISSUE TITLE
Proxy fail open on Mixer internal error: configure network_fail_open option 

### ISSUE THREAD

**Issue by mandarjog** [istio/old_pilot_repo#1053]
This is a follow up to https://github.com/istio/proxy/issues/409.

After the mixer client change, the default is to fail open on a 500 from Mixer. 
A check option `network_fail_open` should be added to filter config.

Related mixerclient PR: https://github.com/istio/mixerclient/pull/96

**Comment by mandarjog** [comment]
Since the default behaviour is as expected, marking this as P2.

**Comment by kyessenov** [comment]
@wenchenglu with fail open, we can't recommend using mixer for any auth policies. is that ok for 0.2?

**Comment by wenchenglu** [comment]
@mandarjog is this option configurable? I think we'd like this to be fail-close if ACL is specified in mixer. Otherwise, this is a big security hole.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1412](https://github.com/istio/istio/issues/1412) via [**ZenHub**](https://www.zenhub.com/)
