### ISSUE TITLE
Create bazel test target for prepare_proxy_test.sh

### ISSUE THREAD

**Issue by ayj** [istio/old_pilot_repo#1095]
Create a bazel test target for [prepare_proxy_test.sh](https://github.com/istio/pilot/blob/master/docker/prepare_proxy_test.sh) to avoid regressions in sidecar iptable rules programming.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1389](https://github.com/istio/istio/issues/1389) via [**ZenHub**](https://www.zenhub.com/)
