### ISSUE TITLE
Check that artifacts and image already exist before pushing them

### ISSUE THREAD

**Issue by sebastienvas** [istio/old_pilot_repo#1109]
This apply to docker and istioctl. We should not attempt to push an image if it already exists. If possible prevent build as well

**Comment by sebastienvas** [comment]
This was not the reason of the issue. This is still a good optimization, but does not need to be done as a P0

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1391](https://github.com/istio/istio/issues/1391) via [**ZenHub**](https://www.zenhub.com/)
