### ISSUE TITLE
Direct route to external TCP services from sidecar

### ISSUE THREAD

**Issue by rshriram** [istio/old_pilot_repo#1126]
We need to be able to reach external HTTP(S) and TCP services via client sidecar. This requires egress rules where user specifies external domains, and ip blocks that need to be passed through -
 using the orig_dst_cluster option in Envoy.

cc @vadimeisenbergibm @saumoh @kyessenov @GregHanson

**Comment by ldemailly** [comment]
is this a solution for #1015 ?

I'm concerned about adding a bunch of features after code complete date

**Comment by rshriram** [comment]
no. This is with respect to egress proxying. This was a big gap in 0.1 and we were waiting on a particular envoy feature to fix this.

**Comment by rshriram** [comment]
this is already being worked on by some folks cc-ed.

**Comment by costinm** [comment]
Alternative is to set the cluster CIDR ?

**Comment by rshriram** [comment]
yep

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1388](https://github.com/istio/istio/issues/1388) via [**ZenHub**](https://www.zenhub.com/)
