### ISSUE TITLE
non-transparent proxy support

### ISSUE THREAD

**Issue by rshriram** [istio/old_pilot_repo#1129]
Allow folks to run envoy without the iptables interception.
1. Requires fixed inbound and outbound port (cluster wide) for HTTP services (partly solved via HTTP_PROXY support)
2. a startup flag in pilot that generates appropriate envoy configs
3. real listeners in the outbound path for tcp services
4. omit tcp listeners in inbound path for tcp services.

With this support, Pilot+Envoy can run on any non-k8s platform. Probably also needs the ability to use custom config at pilot-agent end.
cc @kyessenov

**Comment by ldemailly** [comment]
is this issue to document/cover #1069 ?

**Comment by rshriram** [comment]
it goes beyond that.

**Comment by ldemailly** [comment]
should be for 0.3 then?

**Comment by kyessenov** [comment]
It might happen sooner before final 0.2 release. We'll have several 0.2.x ones.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1390](https://github.com/istio/istio/issues/1390) via [**ZenHub**](https://www.zenhub.com/)
