### ISSUE TITLE
Add watchers for mesh configmap

### ISSUE THREAD

**Issue by rshriram** [istio/old_pilot_repo#1143]
Istio has a global config map that enables/disables mixer, auth, tracing. We need to watch the global mesh configmap for changes. Users adopting istio incrementally (which is the case in production) will not want to bring down all of istio just to enable mixer or auth or tracing in the mesh configmap. If we watch the configmap for changes and react, we can enable mixer without downtime, turn on or turn off auth without having to reinstall istio, enable or disable tracing.

We need not ship this in the very next pre-release, but we definitely need to ship this in the main release (0.2.x) as many bits of our docs would depend on this feature (showcasing incremental istio adoption).

cc @louiscryan @kelseyhightower (relates to the incremental istio adoption conversation),
cc @kyessenov

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1449](https://github.com/istio/istio/issues/1449) via [**ZenHub**](https://www.zenhub.com/)
