### ISSUE TITLE
upgrade google GRPC lib we use

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1167]
Currently we are stuck with grpc 1.2.1, because the grpc > 1.5 is not compatible with gogo.

Find a way to upgarde to newer grpc, get it to support gogo or drop gogo.

go_repository(
    name = "org_golang_google_grpc",
    commit = "8050b9cbc271307e5a716a9d782803d09b0d6f2d",  # v1.2.1
    importpath = "google.golang.org/grpc",
)

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1451](https://github.com/istio/istio/issues/1451) via [**ZenHub**](https://www.zenhub.com/)
