### ISSUE TITLE
support istio quota config: write quota name/amount in Envoy mixer filter

### ISSUE THREAD

**Issue by qiwzhang** [istio/old_pilot_repo#1186]
Now "RequestCount" quota is hard coded in the Envoy Mixer HTTP filter config.   Pilot needs to process istio quota config, and write quota name/amount for each metric in Envoy mixer filter.

**Comment by kyessenov** [comment]
What is the scope of the quota name? Per service, per namespace, per cluster?

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1356](https://github.com/istio/istio/issues/1356) via [**ZenHub**](https://www.zenhub.com/)
