### ISSUE TITLE
Integration test coverage in 0.2.x

### ISSUE THREAD

**Issue by rshriram** [istio/old_pilot_repo#1232]
The following features are not covered by Pilot's integration tests. Need to fix this in the coming weeks to improve test coverage
- [ ] Mongodb/redis filters (@rshriram)
- [x] Egress rules (@rshriram, @vadimeisenbergibm, @elevran  )
- [ ] Consul ( @GregHanson )
- [x] Eureka ( @ijsnellf )

(modified by @kyessenov)

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1454](https://github.com/istio/istio/issues/1454) via [**ZenHub**](https://www.zenhub.com/)
