### ISSUE TITLE
Move to Envoy v2 xDS API

### ISSUE THREAD

**Issue by rshriram** [istio/old_pilot_repo#1257]
Should be fully backward compatible. Lyft folks are going live with it as well. Let's use this issue to track

**Comment by ZackButcher** [comment]
Related, we need to change how Pilot computes Envoy config to move from the pull based model of today to the push based model of the v2 xDS APIs. https://github.com/istio/pilot/issues/1639

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1483](https://github.com/istio/istio/issues/1483) via [**ZenHub**](https://www.zenhub.com/)
