### ISSUE TITLE
Make one script for setting up iptables rules in all repos

### ISSUE THREAD

**Issue by saumoh** [istio/old_pilot_repo#1300]
There are two versions of the prepare_proxy.sh script. One in istio/pilot [1] and another one in istio/proxy[2]
There should be just one such script so that all the testing and changes are managed in one place.
Opening an issue to track this requirement.
[1]: https://github.com/istio/pilot/blob/master/docker/prepare_proxy.sh
[2]: https://github.com/istio/proxy/blob/master/tools/deb/istio-iptables.sh

**Comment by ldemailly** [comment]
subscribe

**Comment by saumoh** [comment]
there are three pieces to it:
- merge the change set from istio/proxy into istio/pilot.
- cross reference the script from  istio/pilot repository in to istio/proxy.
- create or merge tests for functionality in istio/proxy into prepare_proxy_test.sh script.

**Comment by saumoh** [comment]
This issue is blocking pr https://github.com/istio/pilot/pull/1157
Once this is fixed we can merge the above pr.

**Comment by costinm** [comment]
For 0.2, having 2 scripts is intentional, to de-risk the release. 
For 0.3, the intent is to deprecate the old prepare_proxy script - and use the one from proxy (probaby
moved to istio/istio - where most common things are going).

**Comment by kyessenov** [comment]
The script should be where the docker build is. It's here now, so please move the dependencies to pilot repo, so we don't have to make changes to two scripts at the same time.

**Comment by costinm** [comment]
As discussed, pilot should not build iptables images. I will move the new script to istio/istio in 0.3, part of the new flat/consistent build - pilot should build pilot images.

**Comment by kyessenov** [comment]
iptables doesn't have to be in pilot as long as it has stable API/flags
that admission controller can use. Adding istio/istio as a dependency of
pilot introduces a circular dependency that will never resolve through the
bots.

**Comment by costinm** [comment]
Yes, all API, flags and env variables will maintain backward compatibility. 
We are working on flattening the build - so no 'circular dependencies' or bots will be needed
to build iptables.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1384](https://github.com/istio/istio/issues/1384) via [**ZenHub**](https://www.zenhub.com/)
