### ISSUE TITLE
Manifest test failure reasons due to test infra failures 

### ISSUE THREAD

**Issue by xiaolanz** [istio/old_pilot_repo#1302]
modify https://github.com/istio/pilot/blob/master/test/integration/driver.go to clearly delineate if a test died because the test fails or if the test died because of infrastructure setup / teardown.

**Comment by kyessenov** [comment]
How can we tell? If a component fails with panic/segfault, it's indistinguishable from failing from infrastructure failure.

**Comment by xiaolanz** [comment]
I would treat if best efforts.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1366](https://github.com/istio/istio/issues/1366) via [**ZenHub**](https://www.zenhub.com/)
