### ISSUE TITLE
Need an easy way to tell if auth is enabled or not

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1320]
Need to understand if pilot picked up the auth enabled and proxy will encrypt traffic.

Current suggested way was to query RDS, but this is cumbersome.

**Comment by wattli** [comment]
The easiest way is to check pilot policy as shown below.

# Pilot service for discovery
    authPolicy: MUTUAL_TLS

The absolutely correct way is to check CDS/LDS to see if there is ssl_context section in them.

**Comment by andraxylia** [comment]
The authPolicy in the configMap is what has been configured, not what is operational.
If the user changes the configMap and does not restart pilot, auth will not be changed.
A good start can be a log in the pilot, if pilot is the one driving the decision to encrypt or not.

**Comment by andraxylia** [comment]
Also, checking LDS/CDS is not a fast way, one has to know how to do it, it goes too deeply into debugging.

**Comment by wattli** [comment]
I think it's just a one-line command to query LDS/CDS and we can document it in the debugging section.

**Comment by andraxylia** [comment]
If the users needs to run other  kubectl commands to figure ip addresses and do, it is not acceptable.

It's about the time we start adding a command to display operational info about services, and mTLS enabled is one of the fields.

Maybe we can use istioctl for this.

**Comment by andraxylia** [comment]
@wattli can you document it here as well?

**Comment by wattli** [comment]
[lita@lita ~]$ k get configmap istio -o yaml | grep MUTUAL_TLS
    authPolicy: MUTUAL_TLS
      {"apiVersion":"v1","data":{"mesh":"# Uncomment the following line to enable mutual TLS between proxies\nauthPolicy: MUTUAL_TLS\nmixerAddress: istio-mixer:9091\ndiscoveryAddress: istio-pilot:8080\ningressService: istio-ingress\nstatsdUdpAddress: istio-mixer:9125\nzipkinAddress: zipkin:9411"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"istio","namespace":"default"}}

**Comment by wattli** [comment]
or 

$ curl -v http://istio-pilot:8080/v1/clusters/istio-proxy/sidecar~$[VM_IP]~$[SVC].default~cluster.local | grep ssl_context

**Comment by wattli** [comment]
or 

curl -v http://istio-pilot:8080/v1/clusters/istio-proxy/sidecar~$[IP]~$[SVC].default~cluster.local | grep ssl_context

**Comment by andraxylia** [comment]
The configMap show what is configured, not the operational state.

**Comment by wattli** [comment]
The only way I can think of is via LDS/CDS, do you have any suggestions, Andra? One potential way can be let pilot to expose an API to indicate this, but that might be a little strange.

**Comment by ldemailly** [comment]
shouldn't the source envoy be able to tell if it's going to use (m)TLS or not on out calls?
and the destination if it requires it ?

**Comment by mandarjog** [comment]
If we allow enabling auth by service then istioctl could attempt to open an mtls connection to the service using kube port forward.

And then see which certificate it presents. That is proof positive.

**Comment by ldemailly** [comment]
to recap:
- mtls in configmap is the (current) input
- we could devise test that check what happens (like the 2e2 tests I added)
but that's not quite what is asked here which is (imo)
- what is the current live config of a given pilot (for a given envoy)
- what is the current live config of a given envoy

**Comment by kyessenov** [comment]
Port forward in kube is based on socat, and may not play nicely with
iptables. Not sure it's as much proof as trying to connect externally.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1456](https://github.com/istio/istio/issues/1456) via [**ZenHub**](https://www.zenhub.com/)
