### ISSUE TITLE
Ingress only gets IP when it is in the istio-system namespace

### ISSUE THREAD

**Issue by ijsnellf** [istio/old_pilot_repo#1367]
The ingress status syncer tries to grab the IP from `<discovery namespace>/<ingress service>`. We watch for ingress definitions in either all namespaces, or a given user namespace.

**Comment by ijsnellf** [comment]
Might only be in minikube... will verify.

**Comment by andraxylia** [comment]
How is this different from #1021?

Why are the ingress resources definitions relevant to this? They do not participate in the setting of the IP address. Multiple ingress resources can be defined in multiple namespaces, and they will all get the ingress controller's external IP or nodePort.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1457](https://github.com/istio/istio/issues/1457) via [**ZenHub**](https://www.zenhub.com/)
