### ISSUE TITLE
Eureka adapter support for Eureka pre-v1.2.2

### ISSUE THREAD

**Issue by ijsnellf** [istio/old_pilot_repo#1378]
We need to have additional logic to handle pre-v1.2.2 Eureka servers as pointed out here: https://github.com/istio/pilot/pull/994#pullrequestreview-56501078

See https://github.com/hudl/fargo/pull/59 for precedent in handling the differences.

We need to either add logic or switch to fargo/hudl.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1374](https://github.com/istio/istio/issues/1374) via [**ZenHub**](https://www.zenhub.com/)
