### ISSUE TITLE
Pilot discovery doesn't have retries of requests to apiserver

### ISSUE THREAD

**Issue by ijsnellf** [istio/old_pilot_repo#1392]
Noticeable when deploying the Eureka/Consul demos. The API server takes half a second to startup, which means that pilot isn't not able to make the initial request to the apiserver.
```
I1004 20:15:45.779376       1 client.go:169] registering CRD "routerules.config.istio.io"
Error: failed to register custom resources. Post http://istio-apiserver:8080/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 172.18.0.7:8080: getsockopt: connection refused
```

This wouldn't be a big deal in K8S or with Nomad, since the container would restart and work the 2nd time, but you have to restart the container manually in Docker.

**Comment by rshriram** [comment]
This is still an issue as it causes downtime in K8S or Nomad.. Its silly to expect the platform to restart Pilot if it can't reach the API server.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1383](https://github.com/istio/istio/issues/1383) via [**ZenHub**](https://www.zenhub.com/)

**Comment by roommush** [comment]
I have the same problem.
