### ISSUE TITLE
Add liveness and readiness probes to proxies and discovery services

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#1421]
- Add probes to the sidecars, ingress, egress, discovery services, etc.
- Avoid serving traffic with incomplete configuration state.
- Provides signals for horizontal scheduling

Also:
- https://github.com/istio/pilot/issues/908

**Comment by cmluciano** [comment]
/close

dup of #1429

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1472](https://github.com/istio/istio/issues/1472) via [**ZenHub**](https://www.zenhub.com/)
