### ISSUE TITLE
Proxy configuration update without 404

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#1422]
Changes to service, ingresses, or CRDs can cause 404 for live traffic due xDS protocol not staging updates between RDS/CDS/EDS.
Proxy should not apply partial xDS configuration update.

Also:
- https://github.com/istio/pilot/issues/926
- https://github.com/istio/istio/issues/1038
- https://github.com/istio/pilot/issues/1325

**Comment by rshriram** [comment]
isn't this a duplicate of v2 API issue ( #1257 ) ? Because as part of the move, ADS is a natural outcome.

**Comment by kyessenov** [comment]
Yes, it's a dependency, but we need to verify that it solves the issue and add regression tests.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1471](https://github.com/istio/istio/issues/1471) via [**ZenHub**](https://www.zenhub.com/)
