### ISSUE TITLE
istio-initializer fails to initialize jobs

### ISSUE THREAD

**Issue by ayj** [istio/old_pilot_repo#1439]
istio-initializer fails to initialize jobs. The same job can be properly initialized with `istioctl kube-inject` which suggests this is a problem with the initializer specifically and not the overall injection template.

* Steps to reproduce

```bash
kubectl apply -f install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio-initializer.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml
```
The job creation will timeout. The initializer logs show that the apiserver thinks the pod template is invalid.

```bash
E1011 16:16:52.833475       1 initializer.go:154] Job.batch "pi" is invalid: spec.template: Invalid value: api.PodTemplateSpec{ /* ... snip ... */}
```

Discovered in https://github.com/istio/issues/issues/93 but not specific to helm.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1359](https://github.com/istio/istio/issues/1359) via [**ZenHub**](https://www.zenhub.com/)
