### ISSUE TITLE
Namespace annotation for sidecar injection

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1463]
Need to support annotation for sidecar.istio.io/inject for namespaces, similar to the one for workload, but higher precedence. IncludedNamespaces/ExcludedNamespaces are not under the control of the regular user.

https://istio.io/docs/setup/kubernetes/sidecar-injection.html#configuration-options

Moreover, it should work with hierarchical namespaces.

Precedence will be this and should be uniform with other Istio precedence rules:
- workload
- current-namespace
- parent and ancestor namespace up the chain
- includeNamespace/excludeNamespace in the config map
- global policy flag in the config map

**Comment by gyliu513** [comment]
@andraxylia I will work on this in 0.3 release

/cc @ayj @linsun @rshriram

**Comment by andraxylia** [comment]
thanks @gyliu513

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1460](https://github.com/istio/istio/issues/1460) via [**ZenHub**](https://www.zenhub.com/)
