### ISSUE TITLE
Istio injection is not working for modified Deployments.

### ISSUE THREAD

**Issue by ayj** [istio/old_pilot_repo#1477]
@emaildanwilson commented on [Fri Oct 13 2017](https://github.com/istio/istio/issues/1130)

With istio injection running with a setting of `disabled` I'm experiencing an issue where Deployments which are modified to contain `annotations:
    sidecar.istio.io/inject: "true"` do not get injected with envoy. If they are deleted and recreated then the injection works.

The log shows `I1013 20:53:45.569177       1 initializer.go:202] ObjectMeta initializer info extensions/v1beta1, Kind=ReplicaSet central-architecture/mydeployment-62
8804509 policy:"true" status:"" nil`

Is this expected?

**Comment by emaildanwilson** [comment]
I can dig in and try to fix this if you agree it's broke and should work.

**Comment by ayj** [comment]
Copying my response from https://github.com/istio/istio/issues/1130)
> Are you modifying the sidecar.istio.io/inject annotation after the deployment is created? k8s initializers only run when deployments are created.

**Comment by ayj** [comment]
I'm not sure this problem is easily solvable while we're using initializers for automatic injection. However, this may be solvable when add support for mutating webhooks. 

ref https://github.com/istio/pilot/issues/1474

**Comment by linsun** [comment]
I think this is a corner case and we can document as a 0.2 limitation, given we are planning to switch to mutating webhooks also.

**Comment by emaildanwilson** [comment]
Thank you, that makes sense.
I can workaround this for now by changing our deployment process.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1382](https://github.com/istio/istio/issues/1382) via [**ZenHub**](https://www.zenhub.com/)
