### ISSUE TITLE
Relational database adapter for Pilot config store

### ISSUE THREAD

**Issue by shalako** [istio/old_pilot_repo#1557]
Cloud Foundry Routing team is offering to submit a PR for an adapter and runtime options to use it.

Proposal: https://docs.google.com/document/d/16SexdTBgKyhM3ebUB4eVk-lJSXwiCDdJwH3L9yShf5o/edit?usp=sharing

**Comment by kyessenov** [comment]
cc @louiscryan @smawson

**Comment by cmluciano** [comment]
cc @xiaolanz for Config WG

**Comment by cmluciano** [comment]
cc @istio/pilot-hackers

**Comment by shalako** [comment]
In Istio Slack #cloudfoundry, @kyessenov said:
> It seems to me in the same vein as consul/eureka/VM integration - it's fine for custom flags/deployment until we have a proper plugin model generalized in the config group. I would gladly accept contributions, but want to keep config group (@smawson and @louiscryan) in the loop for the architectural direction

Thank you!

**Comment by rshriram** [comment]
This is cool. Looking forward to the PRs. I would suggest getting started with the concrete PRs for platform and config adapters. When the config story materializes, we can align the code, instead of waiting few months for the config system to land.

**Comment by smawson** [comment]
I'm very worried about ecosystem fragmentation if we support multiple configuration APIs for istio. Having multiple config stores will also cause problems for the hybrid / multi-zone configuration model. So I don't think this makes sense to do.

Instead we should just run the istio config API inside cloud foundry, just like we do in all environments. I'd like to understand why that wouldn't be an option here.

**Comment by andraxylia** [comment]
Can you please send the proposal to istio-networking email as well, with a pointer to the issue?

**Comment by shalako** [comment]
We've begun implementation. Our progress can be tracked in https://www.pivotaltracker.com/story/show/151465998

**Comment by smawson** [comment]
Following up on my comment, it sounds like etcd is the primary issue, we should see if we can resolve that in coordination with the config API group.

**Comment by xiaolanz** [comment]
One possible config design is that each zone maintains a separate config store. There is only one "master Galley" exposing config API and rolling out configs to all the zones. The zone-local config store is pluggable, which can be either in etcd or other implementations.  

This way, we don't need to deal with multi-zone distributed config convergence. Each zone will get the performance benefit from local config access.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1378](https://github.com/istio/istio/issues/1378) via [**ZenHub**](https://www.zenhub.com/)
