### ISSUE TITLE
Add a script to query pilot for proxy configurations

### ISSUE THREAD

**Issue by baodongli** [istio/old_pilot_repo#1641]
Per Istio Networking Roadmap: https://docs.google.com/document/d/1oLiEkescgAbUmv7ZsAW-W4_4g4xmrpbnOpyo6yfn06A/edit#heading=h.x9snb54sjlu9, there is a feature in the Debuggability section to introspect on Pilot. Open this issue to track the effort.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1369](https://github.com/istio/istio/issues/1369) via [**ZenHub**](https://www.zenhub.com/)
