### ISSUE TITLE
gRPC-web

### ISSUE THREAD

**Issue by arbarlow** [istio/old_pilot_repo#1663]
As discussed in https://github.com/istio/pilot/issues/928 it would great if Pilot could enable Envoy's gPRC-web filter so that browsers can interact with backend gRPC services directly (useful for admin interfaces etc).

Also, in general, it would great to get a bit more control over Envoy config for filters etc, being a more useful ingress, getting closer to to nginx ingress for usefulness!

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1368](https://github.com/istio/istio/issues/1368) via [**ZenHub**](https://www.zenhub.com/)
