### ISSUE TITLE
Support sharing between TCP and HTTP services

### ISSUE THREAD

**Issue by ayj** [istio/old_pilot_repo#237]
Envoy currently doesn't support using both `tcp_proxy` and `http_connection_manager` filter on the same port for different services. Support for this features requires updating envoy tcp_proxy filter to be optionally non-terminal and fallback to other filters (e.g. HTTP) on the same port. The workaround for this limitation is to not share ports between destination services with different protocols.

**Comment by kyessenov** [comment]
Started https://github.com/lyft/envoy/issues/527 to initiate a design discussion how to handle it properly.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1426](https://github.com/istio/istio/issues/1426) via [**ZenHub**](https://www.zenhub.com/)
