### ISSUE TITLE
Ingress controller: SNI support

### ISSUE THREAD

**Issue by zcahana** [istio/old_pilot_repo#484]
[Ingress spec](https://kubernetes.io/docs/api-reference/v1.6/#ingressspec-v1beta1-extensions) allows for per-host TLS cert/key, which needs to be served on a single port.
Implementation depends on Envoy to support SNI, which is track in lyft/envoy#95.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1424](https://github.com/istio/istio/issues/1424) via [**ZenHub**](https://www.zenhub.com/)
