### ISSUE TITLE
Include root CA file for outgoing HTTPS requests

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#548]
Now that proxies can make HTTPS requests outside the cluster, we need to include a collection of root CAs for the root of trust. We can use the standard debian package and wire a reference to it to `envoy`.

**Comment by rshriram** [comment]
I suggest including the mozilla ca cert bundle that curl uses. https://curl.haxx.se/docs/caextract.html

**Comment by kyessenov** [comment]
This is in reference to egress proxy config as created here:
https://github.com/istio/manager/blob/master/proxy/envoy/egress.go#L104
and end-to-end test here:
https://github.com/istio/manager/blob/master/test/integration/egress.go

We will likely need root CA in the sidecar once we start making out-of-cluster requests from the proxy.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1419](https://github.com/istio/istio/issues/1419) via [**ZenHub**](https://www.zenhub.com/)
