### ISSUE TITLE
Ingress resource: allow URI regexes

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#730]
Requires merging header match conditions to combine with the in-cluster route rules.

**Comment by rshriram** [comment]
not sure if this will work as order of URI matches remains undefined when you have a list of regexes to match. Envoy's semantics is `first regex to match`, while others have longest prefix match.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1416](https://github.com/istio/istio/issues/1416) via [**ZenHub**](https://www.zenhub.com/)
