### ISSUE TITLE
Tracing: sampling and configuration

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#808]
It seems that we might be over-sampling the tracing data, especially the health probes.
We should expose the configuration to sample and filter certain traces.

**Comment by kyessenov** [comment]
ref https://github.com/lyft/envoy/issues/960

**Comment by ijsnellf** [comment]
Currently, we are tracing everything. Envoy has configuration to set the amount of random tracing, but it isn't exposed conveniently right now: https://lyft.github.io/envoy/docs/configuration/http_conn_man/runtime.html#config-http-conn-man-runtime-random-sampling

**Comment by rshriram** [comment]
@ijsnellf Can you file this an issue in Envoy repo and reference this?
-- 

~shriram

**Comment by bobbytables** [comment]
Has anyone come up with a convenient way to disable health check traces at least? I'm worried that we're just bloating our database instance for no reason.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1403](https://github.com/istio/istio/issues/1403) via [**ZenHub**](https://www.zenhub.com/)
