### ISSUE TITLE
Adding Probes to sidecars

### ISSUE THREAD

**Issue by kameshsampath** [istio/old_pilot_repo#908]
I see right now the sidecars does not have liveliness and readiness probes attached to them, sometime when i restart the servers e.g. minikube the apps immediately shows its Running 2/2 but when the apps tries to connect it shows connection refused ...  the `kubectl describe <pod>` shows that its trying to pull images with policy "Always"..

will it be worth to add probes or is there any other rationale behind not adding ?

**Comment by kyessenov** [comment]
Yes, it's definitely worth adding them to the sidecar. Ideally, to the proxy itself, so that k8s awaits for the first successful fetch of RDS/LDS from Envoy.

**Comment by sakshigoel12** [comment]
Please add assignees

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1404](https://github.com/istio/istio/issues/1404) via [**ZenHub**](https://www.zenhub.com/)
