### ISSUE TITLE
Make zone aware load balancing configurable.

### ISSUE THREAD

**Issue by liamawhite** [istio/old_pilot_repo#962]
Enable users to configure `upstream.zone_routing.enabled` and `upstream.zone_routing.min_cluster_size`.

Currently these are only runtime setting, but we have raised an issue against envoy in order to get them configured as config file settings. See [this](https://github.com/lyft/envoy/issues/1344) issue.

**Comment by linsun** [comment]
Chatted with Liam a bit to understand the user impact of this.  Essentially, the default will require 6+ upstream envoy clusters/pods/service instances.  e.g. if a service tries to reach to the review service, the review service needs 6+ pods for this feature to be enabled.  and the default is route is on 100% of traffic to be routed within the AZ.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1444](https://github.com/istio/istio/issues/1444) via [**ZenHub**](https://www.zenhub.com/)
