### ISSUE TITLE
requests looping back through envoy repeatedly

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#978]
`"GET /b HTTP/1.1" 431 - 0 0 67 67 "-" "Go-http-client/1.1" "55548f90-2a21-9840-80fb-9672123adad6" "b.istio-test-fb9t4:8080" "10.60.7.124:8080"` indicates that the request may be looping back through envoy and exceed trace/xff header limits

**Comment by ldemailly** [comment]
this is a super critical issue - at least to understand - if we have loops

**Comment by kyessenov** [comment]
setting use_remote_addr (forcing XFF) is useful to trigger it sometimes, but I can't reproduce it reliably (even after sending 10k requests, and 5 installs)

**Comment by ldemailly** [comment]
dup of #829 ?

**Comment by kyessenov** [comment]
xref https://github.com/linkerd/linkerd/issues/1503

**Comment by sakshigoel12** [comment]
Please update assignees

**Comment by sakshigoel12** [comment]
@andraxylia 
@kyessenov 

can you or do you know who could potentially help here?

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1462](https://github.com/istio/istio/issues/1462) via [**ZenHub**](https://www.zenhub.com/)
