### ISSUE TITLE
Determine correct securityContext for the init container

### ISSUE THREAD

**Issue by cmluciano** [istio/old_pilot_repo#983]
As a followup to #921 & #922 we should determine the exact permissions that the init container needs to function under systems like SELINUX. Since we strive to increase security for others, we should focus on these fine-grained details as well. 

We currently add ```"securityContext":{"capabilities":{"add":["NET_ADMIN"]}``` , but then add ```"privileged":true}```. I believe the privilege escalation trumps any individual securityContext that we list, but I may be wrong.

We need to wade through the SELINUX/Linux capabilities docs to determine what additional settings will allow us to remove the privileged flag.

**Comment by cmluciano** [comment]
Interesting note in kubernetes/kubernetes#33104

>   attempting to create a container with CAP_NET_ADMIN requires this when using docker:

>      securityContext:
>      capabilities:
>        add: ["NET_ADMIN"]

> But requires this when using rkt:

>      securityContext:
>      capabilities:
>         add: ["CAP_NET_ADMIN"]

**Comment by jessfraz** [comment]
@rhatdan @pmorie you might have some insight on the SELinux bits?

**Comment by ayj** [comment]
cc @debianmaster

**Comment by vbatts** [comment]
for finding the capabilities, I recommend checking out this script for [systemtap](http://sourceware.org/systemtap/): https://developers.redhat.com/blog/2017/02/16/find-what-capabilities-an-application-requires-to-successful-run-in-a-container/

**Comment by cmluciano** [comment]
thanks a bunch @vbatts !

**Comment by jessfraz** [comment]
The hero we need and deserve!!!

**Comment by vbatts** [comment]
On Tue, Aug 8, 2017, 15:51 Jess Frazelle <notifications@github.com> wrote:

> The hero we need and deserve!!!


OHMAN

>

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1435](https://github.com/istio/istio/issues/1435) via [**ZenHub**](https://www.zenhub.com/)
